# Generated by Django 5.2.12 on 2026-07-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonneNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(blank=True, help_text='Optionnel', max_length=100)),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('token_desabonnement', models.CharField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Abonné à la newsletter',
                'verbose_name_plural': 'Abonnés à la newsletter',
                'ordering': ['-date_abonnement'],
            },
        ),
        migrations.CreateModel(
            name='EmailNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('envoye_le', models.DateTimeField(auto_now_add=True)),
                ('envoye', models.BooleanField(default=False)),
                ('nb_destinataires', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Email newsletter',
                'verbose_name_plural': 'Emails newsletter',
                'ordering': ['-envoye_le'],
            },
        ),
    ]
